### ISSUE TITLE
import QApplication not working on x64

### ISSUE THREAD

**Issue by ruidc** [pyqt/python-qt5#11]
running the pip version, 0.1.8 and the suggested test code:

```
>>>from PyQt5 import QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```
should I have done any preparation before running the pip command?

**Comment by mottosso** [comment]
No, you're right, I've updated the Readme to the current 5.4 release, but not updated the pip distribution due to some issues.

For the current version, you'll need the Visual C++ 2013 redistributable.
http://www.microsoft.com/en-us/download/details.aspx?id=40784

Sorry about that, it'll go away once 5.4 can be put up on PyPI.

Alternatively, you can pip install from GitHub, which will include it for you (but isn't as well-tested). 

See here: https://github.com/pyqt/python-qt5/issues/7#issuecomment-74143247

Best,
Marcus

**Comment by mottosso** [comment]
Assuming this works for you now.
