### ISSUE TITLE
problem with sip

### ISSUE THREAD

**Issue by seghier** [pyqt/python-qt5#35]
hello ; i use pyinstaller to compile scripts and always i got error that no module named sip
as i know pyqt5 install sip automatically but with this version always the original and old one detected and there is no new version for python 2.7

**Comment by mottosso** [comment]
sip is in the PyQt5 folder, [here](https://github.com/pyqt/python-qt5/blob/master/PyQt5/sip.pyd), it's added at run-time by this plug-in, [here](https://github.com/pyqt/python-qt5/blob/master/PyQt5/__init__.py#L23). You might be able to copy this file or add this path to your pyinstaller destination path. Otherwise you should be able to use your own version, so long as it's the same or newer than [the one included here](https://github.com/pyqt/python-qt5/tree/master/src).

**Comment by seghier** [comment]
thanks ; the problem when i copy the sip included to sitespackages folder i get error ; something about dll or sip not supported; i will try again to create setup of pqt5 from the zip file maybe that install sip

**Comment by seghier** [comment]
when i add sip to the folder of the application another error appear : 
this app failed to start because it could not find or load the Qt platform plugin "windows"

**Comment by seghier** [comment]
is it possible to change the target where sip.pyd will installed ? from Pyqt5 folder to sitespackages folder

**Comment by mottosso** [comment]
You can simply copy/move the file to where you want it. It has no knowledge of where it is, it's simply included in the directory that is being copied to disk when you install this distribution.
